# Generated by Django 5.2.7 on 2025-11-13 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pet Name')),
                ('breed', models.CharField(max_length=100, verbose_name='Breed')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='pet_profiles/', verbose_name='Profile Picture')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Pet Profile',
                'verbose_name_plural': 'Pet Profiles',
                'ordering': ['name'],
            },
        ),
    ]
