# Generated by Django 5.2.7 on 2025-11-13 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Location')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
                ('pets', models.ManyToManyField(blank=True, to='pets.petprofile', verbose_name='Attending Pets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Attending User')),
            ],
            options={
                'verbose_name': 'Event Attendance',
                'verbose_name_plural': 'Event Attendances',
                'ordering': ['event', 'user'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='joined_events', through='events.EventAttendance', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_event_attendance'),
        ),
    ]
