# Generated by Django 5.2.7 on 2026-01-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('groups', '0002_remove_group_admin_group_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='groups.group', verbose_name='Group'),
        ),
    ]
